#!/usr/bin/env python3
"""Build ProfitLeak-AI.html — a single-file version of the app.

Inlines css/styles.css and every js/*.js file into index.html,
producing one portable HTML file you can double-click to run
(without a server and without the folder structure).
Usage:  python3 scripts/build_standalone.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

def main():
    src = ROOT / "index.html"
    html = src.read_text(encoding="utf-8")

    def inline_css(match):
        css = (ROOT / match.group(1)).read_text(encoding="utf-8")
        return "<style>\n" + css + "\n</style>"

    def inline_js(match):
        js = (ROOT / match.group(1)).read_text(encoding="utf-8")
        return "<script>\n" + js + "\n</script>"

    html = re.sub(r'<link rel="stylesheet" href="([^"]+)">', inline_css, html)
    html = re.sub(r'<script src="([^"]+)"></script>', inline_js, html)

    # Safety checks: nothing external may remain, and no raw "</script>"
    # sequence may hide inside the inlined JavaScript.
    assert '<link rel="stylesheet"' not in html, "external stylesheet still referenced"
    assert "<script src=" not in html, "external script still referenced"
    for js_file in sorted((ROOT / "js").glob("*.js")):
        assert "</script" not in js_file.read_text(encoding="utf-8"), f"{js_file.name} contains '</script'"

    banner = ("<!-- ProfitLeak AI - single-file build. AUTO-GENERATED by "
              "scripts/build_standalone.py - edit the source files, then rebuild. -->\n")
    html = html.replace("<!DOCTYPE html>\n", "<!DOCTYPE html>\n" + banner, 1)

    out = ROOT / "ProfitLeak-AI.html"
    out.write_text(html, encoding="utf-8")
    print(f"Built {out.name} ({len(html):,} bytes)")

if __name__ == "__main__":
    sys.exit(main())
